# Exercise 3 - (E7.1)

The required modules:

In [8]:
import numpy as np

from utilities.activation_functions import hardlims

## Point 1

Let's define the problem variables. We then convert the squares into vectors, by scanning them column by column. White squares are represented as $-1$, conversely blue ones as $1$:

In [9]:
p1 = np.array([-1, -1, 1, 1]).reshape(-1, 1)
p2 = np.array([1, 1, -1, 1]).reshape(-1, 1)

The orthogonality can be easily checked by recalling that two vectors are orthogonal if:

$$\begin{equation}
\textbf{p}_1^T \cdot \textbf{p}_2 = 0
\end{equation}$$

In [10]:
# Orthogonality check
print("Dot product: ", np.squeeze(np.dot(p1.transpose(), p2)))

Dot product:  -2


The dot product is not zero, therefore **the two vectors are not orthogonal**.

## Point 2

Using the Hebb rule in the case of __autoassociative network__, thus the output to each input being the input itself, the weight matrix is computed as:

$$ \begin{equation}
    \textbf{W} = \textbf{p}_1\textbf{p}_1^T + \textbf{p}_2\textbf{p}_2^T = \textbf{P}\textbf{P}^T
\end{equation}$$

In [11]:
# Weight matrix
W = np.dot(p1, p1.transpose()) + np.dot(p2, p2.transpose())
print("Hebb W matrix:\n", W)

Hebb W matrix:
 [[ 2  2 -2  0]
 [ 2  2 -2  0]
 [-2 -2  2  0]
 [ 0  0  0  2]]


## Point 3

Let us define the test input pattern $\textbf{p}_t$:

In [12]:
pt = np.array([1, 1, 1, 1]).reshape(-1, 1)

Recovering the implementation of the predict function in the previous exercises, excluding the bias:

In [13]:
# Layer output function
def predict(p: np.ndarray, W_fun: np.ndarray):
    return hardlims(np.dot(W_fun, p.reshape(-1, 1)))

The prediction can be carried out as:

In [14]:
y_pred = predict(pt, W)

print("Prediction: ", np.squeeze(y_pred))

Prediction:  [ 1  1 -1  1]


The prediction is **coincidentally equal** to the input $\textbf{p}_2$, in fact the simple Hebb rule cannot assure the output will correctly match the respective input if those are not orthogonal. When the prototype input patterns are not orthogonal, the Hebb rule produces some errors, and the use of the pseudoinverse rule can reduce errors related to non-orthogonality.